services:
  tonylife-bot:
    container_name: tonylife-bot
    image: allenrkeen/server-bot:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #required
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
